name: Send PR links to Slack
on:
  pull_request:
    branches: ["develop"]
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR urls to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "url": "this is a test",
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_BJSS }}